name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version-file: ./go.mod

      - name: Verify dependencies
        run: go mod verify

      - run: mkdir -p ./files

      - name: golangci-lint
        run: >
          docker run \
            -v ~/go:/root/go \
            -v golangci-lint-cache:/root/.cache \
            -v $(pwd):/app \
            -w /app \
            golangci/golangci-lint:latest-alpine golangci-lint run

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version-file: ./go.mod

      - run: mkdir -p ./files

      - name: Test & Generate Coverage and Report
        run: |
          go test ./...
